apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "Application/Catalog/catalog.yml"

configMapGenerator:
  - name: catalog-config
    files:
      - "Application/application.properties"
    options:
      labels:
        app: catalog
