apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/MohadKamil/PolarDeployment/K8s?ref=master

patches:
- path: patch-environment.yml

configMapGenerator:
- behavior: merge
  files:
  - application-staging.properties
  name: catalog-config
images:
- name: catalog
  newName: catalog
  newTag: pack1.1.0

replicas:
  - name: catalog
    count: 4