apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
selector:
    matchLabels:
spec:
  template:
      spec:
        containers:
        - name: catalog
          env:
            - name: SPRING_PROFILES_ACTIVE     
              value: staging
