version: "3.8"

services:
    catalogAPI:
        depends_on:
            polargres:
                condition: service_healthy
        image: "catalog:pack1.0.0"
        container_name: catalog
        ports:
            - 9001:9001
            - 8001:8001
        environment:
            - BPL_JVM_THREAD_COUNT=50      
            - BPL_DEBUG_ENABLED=true
            - BPL_DEBUG_PORT=8001
            - SPRING_DATASOURCE_URL=jdbc:postgresql://polargres:5432/polar_catalog_db?user=user&password=Password
            - SPRING_PROFILES_ACTIVE=TestData
    polargres:
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5
        # healthcheck:
        #     test: ["CMD", "curl", "-f", "http://polargres:5432"]
        #     interval: 1m30s
        #     timeout: 30s
        #     retries: 5
        #     start_period: 30s
        image: "postgres:15.4"
        container_name: polargres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=Password
            - POSTGRES_DB=polar_catalog_db
        