apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/MohadKamil/PolarDeployment/K8s?ref=master

patches:
  - path: patch-environment.yml
  - path: patch-volumes.yml
  - path: patch-resources.yml

configMapGenerator:
  - behavior: merge
    files:
      - "application-prod.yml"
    name: catalog-config