apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
spec:
  template:
    spec:
      containers:
        - name: catalog
          resources:
            requests:           
              memory: 756Mi     
              cpu: "0.1"          
            limits:             
              memory: 756Mi     
              cpu: "2"