apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  labels:
    app: catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog
  template:
    metadata: 
      labels:                                                
        app: catalog 
    spec:
      containers:                                            
        - name: catalog                                
          image: catalog:pack1.1.0                               
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec: 
                command: [ "sh", "-c", "sleep 5" ]                        
          ports: 
            - containerPort: 9001                              
          env:                                                 
            - name: BPL_JVM_THREAD_COUNT                       
              value: "50" 
            - name: SPRING_DATASOURCE_URL                      
              value: jdbc:postgresql://polargres:5432/polardb_catalog_db?user=user&password=Password 
            - name: SPRING_PROFILES_ACTIVE                     
              value: TestData

---

apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    app: catalog
spec:
  type: ClusterIP
  selector:
    app: catalog
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9001

